### PR TITLE
Add option to allow PicoTLS to be fetched; add public dependencies

### PR DESCRIPTION
**Pull request by paulej**
This PR introduces an option to allow including picoquic into a downstream project using CMake's FetchContent feature.  I left the option OFF by default, so as to not alter current behavior.

### CODE REVIEW

**Review by huitema — COMMENTED** [review]
I will test this changes before commenting more, but as a general feedback: can we update one of the Github actions to build using this new CMake option instead of the current set of shell scripts?

**Comment by paulej** [comment]
Definitely.  I'll look at that in a moment.

**Comment by huitema** [comment]
I tried to build the BR branch on my iMac, and I get the following error:
```
CMake Warning (dev) in CMakeLists.txt:
  Policy CMP0021 is not set: Fatal error on relative paths in
  INCLUDE_DIRECTORIES target property.  Run "cmake --help-policy CMP0021" for
  policy details.  Use the cmake_policy command to set the policy and
  suppress this warning.

  Found relative path while evaluating include directories of
  "picoquic_sample":

    "OPENSSL_INCLUDE_DIR-NOTFOUND"

This warning is for project developers.  Use -Wno-dev to suppress it.

-- Generating done
CMake Generate step failed.  Build files cannot be regenerated correctly.
christianhuitema@Christians-iMac picoquic-paulej % git branch
  master
* paulej_fetch_option
```

Am I doing something wrong?

**Comment by huitema** [comment]
I was using the command:
```
cmake -DPICOQUIC_FETCH_PTLS=ON .
```

**Comment by paulej** [comment]
One of the downstream projects is also failing on Mac. Works fine on Ubuntu (which is what I'm using).  I just made one change in PicoTLS for this sort of include directory issue.  And, there might be another somewhere.

**Comment by huitema** [comment]
My bad. PR branch was not loaded properly. Once it is, I get:
```
CMake Error in CMakeLists.txt:
  Found relative path while evaluating include directories of
  "picoquic_sample":

    "OPENSSL_INCLUDE_DIR-NOTFOUND"



-- Generating done
```

**Comment by paulej** [comment]
What does this line produce?
```cmake
message(STATUS "OpenSSL_INCLUDE_DIR: ${OPENSSL_INCLUDE_DIR}")
```

I assume that might tell us something

**Comment by huitema** [comment]
If I try to "cmake" picots directly on the same Mac, I get:
```
christianhuitema@Christians-iMac picotls % cmake .
-- Detecting USDT support
-- Detecting USDT support - found
-- Enabling USDT support
-- Checking for module 'libbrotlidec'
--   No package 'libbrotlidec' found
-- Checking for module 'libbrotlienc'
--   No package 'libbrotlienc' found
--   Enabling OpenSSL support
-- Configuring done
-- Generating done
-- Build files have been written to: /Users/christianhuitema/Documents/projects/picotls
```

**Comment by paulej** [comment]
Sadly, I'm actually seeing tests fail -- and a core dump -- if I try to run `./picoquic_ct -n -r`.  I'm not sure why.  I got the same result both on my Ubuntu machine as well as a Fedora 36 docker container on the same machine.  I'm puzzled.  Things are building and linking, but I'm not sure why I'd see tests failed. One even core dumps.

**Comment by paulej** [comment]
And, yet all tests here passed. Quite odd.

**Comment by paulej** [comment]
Oh, so the tests assume they are to be run in the source tree.  I was building in a build/ directory and running tests there.

**Comment by paulej** [comment]
```yaml
---
name: "CITests"

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  citests:
    name: CI-Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          # We must fetch at least the immediate parents so that if this is
          # a pull request then we can checkout the head.
          fetch-depth: 2
          submodules: 'recursive'

      - run: |
          sudo apt-get install -y libssl-dev
          cmake -S . -B build -DPICOQUIC_FETCH_PTLS:BOOL=ON
          cmake --build build

      - name: Perform Unit Tests
        run: |
            ulimit -c unlimited -S
            build/picoquic_ct -n -r && QUICRESULT=$?
            build/picohttp_ct -n -r -x http_corrupt && HTTPRESULT=$?
            if [[ ${QUICRESULT} == 0 ]] && [[ ${HTTPRESULT} == 0 ]]; then exit 0; fi;
            exit 1
```

I was going to add this, but I see you just modified the current one.  Which do you prefer?

What is the secret to being in the source tree when running the tests?  I assume a file is being opened or something, but I failed to find it.

**Comment by huitema** [comment]
The test input files and reference output files are in the source tree. The test program needs to find them.
There is an option to tell the test program where to find the source tree:
```
christianhuitema@Christians-iMac picoquic-paulej % ./picoquic_ct -h
PicoQUIC test execution
Usage: picoquic_ct [-x <excluded>] [<list of tests]

Usage: ./picoquic_ct [test1 [test2 ..[testN]]]
...
Options: 
  -x test           Do not run the specified test.
  -s nnn            Run stress for nnn minutes.
  -f nnn            Run fuzz for nnn minutes.
  -c nnn ccc        Run connection stress for nnn minutes, ccc connections.
  -d ppp uuu dir    Run connection ddoss for ppp packets, uuu usec intervals,
  -F nnn            Run the corrupt file fuzzer nnn times,
                    logs in dir. No logs if dir="-"
  -n                Disable debug prints.
  -r                Retry failed tests with debug print enabled.
  -h                Print this help message
  -S solution_dir   Set the path to the source files to find the default files
```

**Comment by huitema** [comment]
As for the option, let's modify the existing one. Adding more workflows with consume too much resource. I think your version as a bit more precision -- can you add the missing data to the existing test?

**Review by huitema — APPROVED** [review]

**Pull request merged**
