### PR TITLE
Zero cid migration

### PR DESCRIPTION
**Pull request by huitema**
Adding tests for migration with zero-length client CID.

### CODE REVIEW

**Comment by huitema** [comment]
@martinthomson This PR adds three tests of migration, NAT rebinding and preferred address migration with the constraint that the client uses zero-length CID. The tests pass. Does that alleviate your concerns about these scenarios?

**Comment by huitema** [comment]
Close #1088

**Review by martinthomson — APPROVED** [review]
More testing 👍 

It seems like you had close to the some bug as everyone else though.

**Comment by huitema** [comment]
@martinthomson The only changed I made in the actual code was to allow the client to engage in migrations even if the client CID length was set to 0. The previous code would just consider setting "cid length=0" to imply "no migrations". With that, the tests verify that NAT rebinding, explicit migration and preferred address migration work. I also verified manually that the client modified with this PR can do NAT rebinding and explicit migration against the not-yet-modified QUIC server.

During your previous tests, were you testing the neqo client against the picoquic server, or the picoquic client against the neqo server? If there is an issue that I did not capture, I need to reproduce it now.

By the way, I saw an interesting issue when testing from home. The client's PATH CHALLENGE are fully padded. The ACKs sent on the old port prior to the challenge response are not. The network manages to send all the short packets before the long ones, leading to "far away" our of order delivery of the path challenge!

**Comment by huitema** [comment]
Close #1088

**Comment by martinthomson** [comment]
I didn't test picoquic.  I was using public services.  I can try to find time to test picoquic if you think that would help.

**Comment by huitema** [comment]
Also fixed the migration code, to only migrate after receiving non-migration packets. The previous code was migrating immediately after receiving a challenge response. That could cause a "migration bounce" if packets were received out of order. The rule is only enforced on the server side, since the client intention is to migrate. It is not enforced for NAT rebinding, because that causes too many packet losses.

**Pull request merged**
